const get = (res,res,next)=>{
    try {
        
    } catch (error) {
        next(error);
    }
}